name: Publish Module

on:
  push:
    paths:
    - 'cosmos-db/cosmos-db.psd1'
    branches: 
    - main

  workflow_dispatch:

jobs:
  publish-module:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Get module versions
      id: check_versions
      uses: cmbrose/compare-ps-module-version-to-marketplace@v1.1
      with:
        moduleName: cosmos-db
    
    - if: ${{ steps.check_versions.outputs.should_publish }}
      name: Publish Module to PowerShell Gallery
      uses: pcgeek86/publish-powershell-module-action@v19
      id: publish-module
      with:
        modulePath: cosmos-db
        NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }}
        
    - if: ${{ steps.check_versions.outputs.should_publish }}
      name: Update Release Tag
      shell: pwsh
      run: |
        $version = ${{ steps.check_versions.outputs.repo_version }}
        git tag "v$version"
        git push origin --tags
